"""init models

Revision ID: 8c9e1ad4d5db
Revises: 
Create Date: 2025-01-12 00:30:34.053219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c9e1ad4d5db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecommerce',
    sa.Column('id_ecommerce', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_ecommerce')
    )
    op.create_table('products',
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('id_user', sa.String(length=255), nullable=False),
    sa.Column('id_ecommerce', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ecommerce'], ['ecommerce.id_ecommerce'], ),
    sa.PrimaryKeyConstraint('id_product')
    )
    op.create_table('price_history',
    sa.Column('id_history', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('query_date', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_offer', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_product'], ['products.id_product'], ),
    sa.PrimaryKeyConstraint('id_history')
    )
    op.create_table('tracker',
    sa.Column('id_tracker', sa.Integer(), nullable=False),
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('execution_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_product'], ['products.id_product'], ),
    sa.PrimaryKeyConstraint('id_tracker')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracker')
    op.drop_table('price_history')
    op.drop_table('products')
    op.drop_table('ecommerce')
    # ### end Alembic commands ###
